name: CMake GH Actions

on: push

jobs:
  build-linux-gcc:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repository
        run: |
            git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise && cd hyrise
            git checkout ${GITHUB_REF#refs/heads/}

      - name: Install Dependencies
        run: sudo apt-get install --no-install-recommends -y libaio-dev autoconf bash-completion bc clang-11 clang-14 clang-format-14 clang-tidy-14 cmake curl dos2unix g++-9 gcc-9 g++-11 gcc-11 gcovr git graphviz libboost-all-dev libhwloc-dev libncurses5-dev libnuma-dev libnuma1 libpq-dev libreadline-dev libsqlite3-dev libtbb-dev lld man ninja-build parallel python3 python3-pip valgrind

      - name: Install umap
        run: |
            git clone https://github.com/LLNL/umap.git umap && cd umap
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
            sudo make install

      - name: Run Make with gcc
        run: |
            cd ${{github.workspace}}/hyrise/
            mkdir cmake-build-debug-gcc && cd cmake-build-debug-gcc
            cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
            ninja
      
      - name: Run Unit Tests with gcc
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-gcc
            ./hyriseTest

      - name: Run TPCH (SF 0.1)
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-gcc
            ./hyriseBenchmarkTPCH -r 1 -s 0.1
    
  build-linux-clang:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repository
        run: |
            git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise && cd hyrise
            git checkout ${GITHUB_REF#refs/heads/}

      - name: Install Dependencies
        run: sudo apt-get install --no-install-recommends -y libaio-dev autoconf bash-completion bc clang-11 clang-14 clang-format-14 clang-tidy-14 cmake curl dos2unix g++-9 gcc-9 g++-11 gcc-11 gcovr git graphviz libboost-all-dev libhwloc-dev libncurses5-dev libnuma-dev libnuma1 libpq-dev libreadline-dev libsqlite3-dev libtbb-dev lld man ninja-build parallel python3 python3-pip valgrind

      - name: Install umap
        run: |
            git clone https://github.com/LLNL/umap.git umap && cd umap
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
            sudo make install

      - name: Run Make with clang
        run: |
            cd ${{github.workspace}}/hyrise/
            mkdir cmake-build-debug-clang && cd cmake-build-debug-clang
            cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang  -DCMAKE_CXX_COMPILER=clang++ ..
            ninja

      - name: Run Unit Tests with clang
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-clang
            ./hyriseTest
      
      - name: Run TPCH (SF 0.1)
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-clang
            ./hyriseBenchmarkTPCH -r 1 -s 0.1 

  build-mac-clang:
    runs-on: macos-latest

    steps:
      - name: Clone Repository
        run: |
            git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise && cd hyrise
            git checkout ${GITHUB_REF#refs/heads/}

      - name: Install Dependencies
        run: brew install llvm autoconf boost cmake coreutils dos2unix graphviz libpq ncurses parallel pkg-config postgresql readline sqlite3 tbb && brew install ninja

      - name: Run Make with clang
        run: |
            cd ${{github.workspace}}/hyrise/
            mkdir cmake-build-debug-clang && cd cmake-build-debug-clang
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" -GNinja ..
            ninja

      - name: Run Unit Tests with clang
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-clang
            ./hyriseTest

      - name: Run TPCH (SF 0.1)
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-clang
            ./hyriseBenchmarkTPCH -r 1 -s 0.1 