name: CMake GH Actions

on: push

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Repository
        run: git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise && cd hyrise

      - name: Install Dependencies
        run: sudo apt-get install --no-install-recommends -y autoconf bash-completion bc clang-11 clang-14 clang-format-14 clang-tidy-14 cmake curl dos2unix g++-9 gcc-9 g++-11 gcc-11 gcovr git graphviz libboost-all-dev libhwloc-dev libncurses5-dev libnuma-dev libnuma1 libpq-dev libreadline-dev libsqlite3-dev libtbb-dev lld man ninja-build parallel python3 python3-pip valgrind

      - name: Install umap
        run: |
            git clone https://github.com/LLNL/umap.git umap && cd umap
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
            sudo make install

      - name: Run Make with clang
        run: |
            cd ${{github.workspace}}/hyrise/
            mkdir cmake-build-debug-clang && cd cmake-build-debug-clang
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
            make  -j

      - name: Run Make with gcc
        run: |
            cd ${{github.workspace}}/hyrise/
            mkdir cmake-build-debug-gcc && cd cmake-build-debug-gcc
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
            make -j

      - name: Run Unit Tests with clang
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-clang
            ./hyriseTest
      
      - name: Run Unit Tests with gcc
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug-gcc
            ./hyriseTest

  passive-aggressive-comments:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with: 
          days-before-pr-stale: -7
          stale-pr-message: "Am I so worthless that nobody wants to commit to me?"
          stale-pr-label: "unloved"
          days-before-issue-stale: -7
          stale-issue-message: "I know I am just an issue, but could still give me some attention?"
          stale-issue-label: "unloved"